version: "1.0"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
  degarden:
    container_name: degarden
    image: mthuandkp/degarden-api:v1.0
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysqldb
    deploy:
      resources:
        limits:
          cpus: "1"    # Limit to 1 CPU core
          memory: 1G   # Limit to 1GB of memory