version: "1.0"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQLDB_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10

  degarden:
    container_name: degarden
    image: mthuandkp/degarden-api:v1.0
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysqldb:
          condition: service_healthy